# Generated by Django 5.0.7 on 2026-07-31 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_feedback_likes_alter_feedback_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='admin_reply',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='feedback',
            name='admin_reply_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='clap_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='feedback',
            name='laugh_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='feedback',
            name='wow_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
